### ISSUE TITLE
Document the SEO related stuff

### ISSUE THREAD

**Issue by abdonrd** [IBM/pwa-lit-template#11]
* The [`page-not-found.ts`](https://github.com/IBM/pwa-lit-template/blob/master/src/pages/page-not-found.ts) add the `render:status_code`

* The [`page-element.ts`](https://github.com/IBM/pwa-lit-template/blob/master/src/helpers/page-element.ts) update the HTML meta tags based on the route `metatada` property. Also the user can override the `metadata()` method to use dynamic data.

* The [`renderPageNotFound` helper](https://github.com/IBM/pwa-lit-template/blob/master/src/helpers/render-page-not-found.ts). The user can use this helper in the `render()` method in a page. For example, in a user route when the user doesn't exists. We will know that the user does not exist after making the request to the API.

    Related Vaadin Router issue: https://github.com/vaadin/vaadin-router/issues/408

**Comment by web-padawan** [comment]
> The renderPageNotFound helper. The user can use this helper in the render() method in a page. For example, in a user route when the user doesn't exists. We will know that the user does not exist after making the request to the API.

One thing to consider is that navigation should probably still point to the correct page, see the example:

![notfound](https://user-images.githubusercontent.com/10589913/88288216-1dae2b80-ccfc-11ea-9853-7c0c6eb7a346.png)

This can be achieved differently, depending on the way the app is implemented:

1. If the app shell with navigation is **outside** the router outlet, then you can use `renderPageNotFound` as you do.
2. If **every view** is responsible of rendering navigation, then "page not found" should be rendered by the view itself.

In the above example (the app I used to work on), the second approach is used. IMO it is more flexible, because it allows to use different layouts, e.g. with or without drawer, depending on the view - for example, in case of unauthorised user.
